# Generated by Django 5.0.2 on 2024-03-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_failure', '0001_initial'),
        ('module_machine', '0001_initial'),
        ('module_ticket', '0002_alter_ticket_options_ticket_created_ticket_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_failure.failure'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_machine.machine'),
        ),
        migrations.DeleteModel(
            name='Failure',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
