# Generated by Django 5.0.2 on 2024-03-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_machinelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineList',
            new_name='Machine',
        ),
    ]
