# Generated by Django 5.0.2 on 2024-03-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_failure_ticket_delete_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='category',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.failure'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.machine'),
        ),
    ]
